name: Test Wacky Workbench

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install xvfb libfuse2

    - name: Install FreeCAD
      run: |
        wget https://github.com/FreeCAD/FreeCAD/releases/download/0.21.1/FreeCAD_0.21.1-Linux-x86_64.AppImage
        chmod u+x FreeCAD_0.21.1-Linux-x86_64.AppImage
        ln -s "$(realpath FreeCAD_0.21.1-Linux-x86_64.AppImage)" /usr/local/bin/freecad

    - name: Make Mod directory
      run: mkdir -p ~/.local/share/FreeCAD/Mod

    - uses: actions/checkout@v3
      with:
        path: Wacky

    - uses: actions/checkout@v3
      with:
        path: Assembly4
        repository: "Zolko-123/FreeCAD_Assembly4"

    - name: Move repos & Debug
      working-directory: ${{ github.workspace }}
      run: |
        mv Wacky ~/.local/share/FreeCAD/Mod
        mv Assembly4 ~/.local/share/FreeCAD/Mod
        realpath ~/.local/share/FreeCAD/Mod
        ls ~/.local/share/FreeCAD/Mod
        echo $PATH
        ls -l /usr/local/bin/freecad
        freecad -c --dump-config

    - name: Run tests
      run: |
        cd ~/.local/share/FreeCAD/Mod/Wacky
        pwd
        xvfb-run freecad test/TestStraightCut.FCMacro
