name: Test Wacky Workbench

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:freecad-maintainers/freecad-stable
        sudo apt-get update
        sudo apt-get install freecad xvfb

    - name: Make Mod directory
      run: mkdir -p ~/.local/share/FreeCAD/Mod

    - uses: actions/checkout@v3
      with:
        path: Wacky

    - uses: actions/checkout@v3
      with:
        path: Assembly4
        repository: "Zolko-123/FreeCAD_Assembly4"

    - name: Move repos & Debug
      working-directory: ${GITHUB_WORKSPACE}
      run: |
        mv Wacky ~/.local/share/FreeCAD/Mod
        mv Assembly4 ~/.local/share/FreeCAD/Mod
        realpath ~/.local/share/FreeCAD/Mod
        ls ~/.local/share/FreeCAD/Mod
        freecadcmd --dump-config

    - name: Run tests
      working-directory: ~/.local/share/FreeCAD/Mod/Wacky
      run: |
        pwd
        xvfb-run freecad test/TestStraightCut.FCMacro
